# title

blablabla

$$\int_{-\infty}^{+\infty} e^x dx$$

In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt
import time
from tqdm import tqdm
from scipy.stats import bernoulli

def space_env(L , mu=0.5):
    total_space = np.arange(L)
    space = np.random.choice(total_space, int(L*mu), replace=False)  # choose L/2 of the bins to contain a particle
    return(np.sort(space))                                           # return the index of the particles sorted

# example of use

# defining parameters
L = 10      # number of size space simulated

test = space_env(L)
print(test)
mu = 0.2
test2 = space_env(L,mu)
print(test2)

[0 1 2 7 9]
[6 8]


In [3]:

def moves(space,s,left_drift=1/3, right_drift=2/3,v=1):
    # s is the number of steps of the random walk
    numb_particle = len(space)
    particles_index = np.arange(numb_particle)
    particles_number_steps = np.random.poisson(v*numb_particle,s)+2
    print('particles steps',particles_number_steps)
    total = np.cumsum(particles_number_steps)
    to_move = np.random.choice(particles_index,total[-1])
    directions = np.random.choice([-1,1],total[-1])

    print(to_move)
    print(directions)

    # if L is the total number of particles in the environment, 
    # environment partcles receive index in [0,1, ... , L-1]
    # random walk will receive index L = numb_particle
    for n in total: 
        to_move[n-2] = numb_particle  
        to_move[n-1] = numb_particle+1
        dir_l = bernoulli.rvs(left_drift)
        dir_r = bernoulli.rvs(right_drift)
        dir_l = 2*dir_l -1
        dir_r = 2*dir_r -1
        directions[n-2]  = dir_l
        directions[n-1]= dir_r
    
    print(to_move)
    print(directions)

space = space_env(8)
moves(space,2)

particles steps [7 6]
[1 1 3 3 2 3 3 2 1 3 1 2 2]
[-1  1 -1 -1 -1  1  1 -1  1 -1 -1 -1 -1]
[1 1 3 3 2 4 5 2 1 3 1 4 5]
[-1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1]
